In [25]:
import numpy as np
a = np.arange(1, 9)
print(a)

a=np.arange(30)
k=np.arange(2,6)
b=a[5:16]
c=a[::2]
print("original array",a)
print("nums between 5 to 15 ",b)
print("every second element: ",c)
print(k)
print(end=" \n")

a=np.zeros((3,3))
print(a)

print("\n")
a=np.identity(3)
print(a)

print(" ")
a1=np.eye(3)
print("eye ",a1)


[1 2 3 4 5 6 7 8]
original array [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
nums between 5 to 15  [ 5  6  7  8  9 10 11 12 13 14 15]
every second element:  [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]
[2 3 4 5]
 
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
 
eye  [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [20]:
from numpy import random
x=random.randint(100,size=(5))
print(x)
print("\n")
y=random.randint(100,size=(2,5))
print(y)

print("\n")
z=random.rand(5)
print(z)

print("\n")
x=random.choice([3,24,57,85])
print(x)

[ 1 11  9 61 13]


[[23 96 38 89 55]
 [84 21 65 93 72]]


[0.18561223 0.73924441 0.17995491 0.46372166 0.75799705]


85


In [22]:
x=random.choice([2,7,4,22],size=(3,5))
print(x)

[[22  2 22  7  7]
 [ 2  2 22  4  4]
 [ 2  7  4  2 22]]
