In [3]:
import numpy as np
from numpy import random
m1=random.randint(1,11,size=(3,3))
m2=random.randint(1,11,size=(3,3))
dot_product=np.dot(m1,m2)
print("Matrix 1:")
print(m1)
print("Matrix 2:")
print(m2)
print("Dot Product of matrix 1 and matrix 2:")
print(dot_product)

for i in range(3):
    for j in range(3):
        print(f"Element [{i},{j}] = dot({m1[i,:]}, {m2[:,j]})")


Matrix 1:
[[ 9  7  7]
 [ 4  3 10]
 [ 7  4  7]]
Matrix 2:
[[ 4  8 10]
 [ 4  1  6]
 [ 9  1  4]]
Dot Product of matrix 1 and matrix 2:
[[127  86 160]
 [118  45  98]
 [107  67 122]]
Element [0,0] = dot([9 7 7], [4 4 9])
Element [0,1] = dot([9 7 7], [8 1 1])
Element [0,2] = dot([9 7 7], [10  6  4])
Element [1,0] = dot([ 4  3 10], [4 4 9])
Element [1,1] = dot([ 4  3 10], [8 1 1])
Element [1,2] = dot([ 4  3 10], [10  6  4])
Element [2,0] = dot([7 4 7], [4 4 9])
Element [2,1] = dot([7 4 7], [8 1 1])
Element [2,2] = dot([7 4 7], [10  6  4])


In [5]:
import numpy as np
a=np.arange(30)
b=a[15:16]
c=a[::2]
print("Original Array: ",a)
print("Numbers between indices 5 to 15: ",b)
print("Every second element from the array: ",c)


Original Array:  [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]
Numbers between indices 5 to 15:  [15]
Every second element from the array:  [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [6]:
import numpy as np
id=np.eye(3)
print(id)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [9]:
import numpy as np
a=np.arange(1,6)
print(a)
b=np.arange(10,15,10)
print(b)
add=a+b
sub=a-b
mul=a*b
div=a/b
print("Addition: ",add)
print("Substraction: ",sub)
print("Multiplication: ",mul)
print("Division: ",div)

[1 2 3 4 5]
[10]
Addition:  [11 12 13 14 15]
Substraction:  [-9 -8 -7 -6 -5]
Multiplication:  [10 20 30 40 50]
Division:  [0.1 0.2 0.3 0.4 0.5]


In [11]:
import math

def standard_deviation(data):
    if len(data)==0:
        return 0
    mean=sum(data)/len(data)
    variance=sum((x-mean)** 2 for x in data)/len(data)
    return math.sqrt(variance)

num=[10,12,23,16,23,21,16]
print("Standard Deviation: ",standard_deviation(num))


Standard Deviation:  4.831867007225076


In [12]:
import numpy as np
from numpy import random
mat=random.randint(1,11,size=(2,3))
tp1=np.transpose(mat)
tp2=mat.T
print("Original Matrix:")
print(mat)
print("Transposed of the Matrix:")
print(tp1)
print("Transposed using .T attribute:")
print(tp2)


Original Matrix:
[[4 6 5]
 [1 1 1]]
Transposed of the Matrix:
[[4 1]
 [6 1]
 [5 1]]
Transposed using .T attribute:
[[4 1]
 [6 1]
 [5 1]]


In [13]:
import numpy as np
from numpy import random
a=random.randint(1,20,size=(4,4))
sum_matrix=np.sum(a)
mean_matrix=np.mean(a)
min_matrix=np.min(a)
max_matrix=np.max(a)
row_sum=np.sum(a,axis=1)
col_sum=np.sum(a,axis=0)
print("4*4 matrix with random integers:")
print(a)
print("Sum of all elements: ",sum_matrix)
print("Mean of all elements: ",mean_matrix)
print("Maximum element: ",max_matrix)
print("Column-wise sum:",col_sum)
print("Row-wise sums:",row_sum)


4*4 matrix with random integers:
[[15  8 19  3]
 [10 13 10 13]
 [14  8 10  7]
 [16  1  6 10]]
Sum of all elements:  163
Mean of all elements:  10.1875
Maximum element:  19
Column-wise sum: [55 30 45 33]
Row-wise sums: [45 46 39 33]


In [3]:
from numpy import random
x=random.choice([3,5,7,9])
print(x)

9


In [4]:
y=random.choice([3,5,7,9],size=(3,5))
print(y)

[[3 3 3 3 5]
 [5 3 5 7 9]
 [3 5 3 9 9]]


In [ ]:
a=random.rand(3,3)
print(a)


[[0.00803913 0.68645805 0.62829722]
 [0.14938596 0.1568295  0.07447487]
 [0.69559283 0.34850446 0.16701405]]


In [15]:
import numpy as np
from numpy import random
r=np.arange(1,100)
m1=np.mean(r)
m2=np.median(r)
m3=np.std(r)
m4=np.var(r)
print("Mean:",m1)
print("median:",m2)
print("standard deviation:",m3)
print("variance:",m4)
print("Standard deviation:",r)


Mean: 50.0
median: 50.0
standard deviation: 28.577380332470412
variance: 816.6666666666666
Standard deviation: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96
 97 98 99]


In [ ]:
import numpy as np
a=np.array([5,4,6,3,7]) #a is a 1D array representating a signal in the time domain
gfg=np.fft.fft(a) #fast fourier transform 
print(gfg)

[25.        +0.j          1.11803399+1.08981379j -1.11803399+4.61652531j
 -1.11803399-4.61652531j  1.11803399-1.08981379j]


In [3]:
import numpy as np
n=8
t=np.arange(n)
f=np.sin(2*np.pi*t/n)
ft=np.fft.fft(f)
print(ft)

[ 1.22464680e-16+0.00000000e+00j -3.44509285e-16-4.00000000e+00j
  1.22464680e-16-2.22044605e-16j  9.95799250e-17+0.00000000e+00j
  1.22464680e-16+0.00000000e+00j  9.95799250e-17+0.00000000e+00j
  1.22464680e-16+2.22044605e-16j -3.44509285e-16+4.00000000e+00j]


In [ ]:
import numpy as np
arr=np.array([1,2,3,4,5,4,4])
x=np.where(arr==4)
print(x)

y=np.where(arr%2==0)
print(y)
z=np.where(arr%2==1)
print(z)
print(np.sort(arr))

arr=

(array([3, 5, 6], dtype=int64),)
(array([1, 3, 5, 6], dtype=int64),)
(array([0, 2, 4], dtype=int64),)
[1 2 3 4 4 4 5]
