In [1]:
import numpy as np
arr=np.arange(10)
print(arr)

[0 1 2 3 4 5 6 7 8 9]


In [2]:
import numpy as np
zero=np.zeros((3,3))
print(zero)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


In [3]:
import numpy as np
id=np.eye(3)
print(id)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [4]:
arr2=np.arange(1,6)
arr3=np.arange(10,15)
print(arr2)
print(arr3)

[1 2 3 4 5]
[10 11 12 13 14]


In [5]:
print("\nAddition:", arr2 + arr3)
print("Subtraction:", arr2 - arr3)
print("Multiplication:", arr2 * arr3)
print("Division:", arr2 / arr3)


Addition: [11 13 15 17 19]
Subtraction: [-9 -9 -9 -9 -9]
Multiplication: [10 22 36 52 70]
Division: [0.1        0.18181818 0.25       0.30769231 0.35714286]


In [6]:
arr4 = np.arange(30)
print("\n1D Array (0–29):\n", arr4)

# Slice elements between indices 5 and 15
slice_part = arr4[5:16]
print("\nElements between indices 5 and 15:", slice_part)

# Extract every second element
every_second = arr4[::2]
print("\nEvery second element:", every_second)


1D Array (0–29):
 [ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29]

Elements between indices 5 and 15: [ 5  6  7  8  9 10 11 12 13 14 15]

Every second element: [ 0  2  4  6  8 10 12 14 16 18 20 22 24 26 28]


In [7]:
# Create a 3x3 array with random values between 0 and 10
random_matrix = np.random.randint(0, 11, (3, 3))
print("3x3 Random Matrix (0–10):\n", random_matrix)


3x3 Random Matrix (0–10):
 [[4 6 4]
 [8 4 8]
 [6 5 5]]


In [8]:
# Extract the first two rows and first two columns
sub_matrix = random_matrix[:2, :2]
print("\nFirst two rows & first two columns:\n", sub_matrix)


First two rows & first two columns:
 [[4 6]
 [8 4]]


In [9]:
# Extract the last row
last_row = random_matrix[-1, :]
print("\nLast row:\n", last_row)


Last row:
 [6 5 5]


In [10]:
arr = np.arange(1, 13)
print("\n1D Array (12 elements):\n", arr)

# Reshape into a 3x4 matrix
reshaped_matrix = arr.reshape(3, 4)
print("\nReshaped 3x4 Matrix:\n", reshaped_matrix)


1D Array (12 elements):
 [ 1  2  3  4  5  6  7  8  9 10 11 12]

Reshaped 3x4 Matrix:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [11]:
# Create a 4x4 matrix with random integers between 1 and 20
matrix_4x4 = np.random.randint(1, 21, (4, 4))
print("\n4x4 Random Matrix (1–20):\n", matrix_4x4)

# Aggregation functions
print("\nSum of all elements:", np.sum(matrix_4x4))
print("Mean of all elements:", np.mean(matrix_4x4))
print("Max of all elements:", np.max(matrix_4x4))
print("Min of all elements:", np.min(matrix_4x4))

# Row-wise and column-wise sum
print("\nRow-wise sum:", np.sum(matrix_4x4, axis=1))
print("Column-wise sum:", np.sum(matrix_4x4, axis=0))


4x4 Random Matrix (1–20):
 [[ 6 15 18 15]
 [14 14 15 11]
 [ 1  3 15 19]
 [12 13 20 19]]

Sum of all elements: 210
Mean of all elements: 13.125
Max of all elements: 20
Min of all elements: 1

Row-wise sum: [54 54 38 64]
Column-wise sum: [33 45 68 64]


In [12]:
import numpy as np

# --------------------------
# Task 7
# --------------------------
# Create two 3x3 matrices
mat1 = np.random.randint(1, 10, (3, 3))
mat2 = np.random.randint(1, 10, (3, 3))

print("Matrix 1:\n", mat1)
print("\nMatrix 2:\n", mat2)

# Dot product
dot_product = np.dot(mat1, mat2)
print("\nDot Product (Matrix1 • Matrix2):\n", dot_product)

# Create a 2x3 matrix
mat3 = np.random.randint(1, 10, (2, 3))
print("\n2x3 Matrix:\n", mat3)

# Transpose
transpose_mat3 = mat3.T
print("\nTranspose of 2x3 Matrix:\n", transpose_mat3)


# --------------------------
# Task 8
# --------------------------
# Generate an array of 10 random integers between 1 and 100
arr_rand = np.random.randint(1, 101, 10)
print("\n1D Array of 10 random integers (1–100):\n", arr_rand)

# Create a 2D NumPy array (3x4) with random integers between 10 and 50
arr_2d = np.random.randint(10, 51, (3, 4))
print("\n2D Array (3x4) with random integers (10–50):\n", arr_2d)

Matrix 1:
 [[3 9 8]
 [8 8 6]
 [1 6 6]]

Matrix 2:
 [[7 8 6]
 [5 7 8]
 [9 9 8]]

Dot Product (Matrix1 • Matrix2):
 [[138 159 154]
 [150 174 160]
 [ 91 104 102]]

2x3 Matrix:
 [[3 9 9]
 [9 7 3]]

Transpose of 2x3 Matrix:
 [[3 9]
 [9 7]
 [9 3]]

1D Array of 10 random integers (1–100):
 [59 12  5 67 74 89 89 87 80 20]

2D Array (3x4) with random integers (10–50):
 [[47 28 30 43]
 [24 29 16 16]
 [34 40 25 41]]


In [13]:
import numpy as np

# --------------------------
# Task 9
# --------------------------
# Create a 2D array (3x3) with random float values between 0 and 1
random_floats = np.random.rand(3, 3)
print("3x3 Random Float Matrix (0–1):\n", random_floats)


# --------------------------
# Task 10
# --------------------------
# Generate 1000 random numbers between 0 and 100
large_array = np.random.randint(0, 101, 1000)

# Compute standard deviation and variance
std_dev = np.std(large_array)
variance = np.var(large_array)

print("\nStandard Deviation of array:", std_dev)
print("Variance of array:", variance)


# --------------------------
# Task 11
# --------------------------
# Create two matrices of the same dimension using numpy.array()
matrix_a = np.array([[1, 2, 3],
                     [4, 5, 6],
                     [7, 8, 9]])

matrix_b = np.array([[9, 8, 7],
                     [6, 5, 4],
                     [3, 2, 1]])

# Add the two matrices
matrix_sum = matrix_a + matrix_b

print("\nMatrix A:\n", matrix_a)
print("\nMatrix B:\n", matrix_b)
print("\nSum of Matrix A and Matrix B:\n", matrix_sum)

3x3 Random Float Matrix (0–1):
 [[0.29711986 0.06757268 0.41950524]
 [0.41060586 0.96094232 0.09467198]
 [0.63834777 0.00173731 0.13582214]]

Standard Deviation of array: 29.453177146107684
Variance of array: 867.489644

Matrix A:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Matrix B:
 [[9 8 7]
 [6 5 4]
 [3 2 1]]

Sum of Matrix A and Matrix B:
 [[10 10 10]
 [10 10 10]
 [10 10 10]]


In [14]:
import numpy as np

# --------------------------
# Task 12
# --------------------------
# Create two matrices of the same dimension
mat1 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90]])

mat2 = np.array([[5, 4, 3],
                 [2, 1, 0],
                 [9, 8, 7]])

# Subtract mat2 from mat1
sub_result = mat1 - mat2
print("Matrix 1:\n", mat1)
print("\nMatrix 2:\n", mat2)
print("\nSubtraction (Matrix1 - Matrix2):\n", sub_result)

Matrix 1:
 [[10 20 30]
 [40 50 60]
 [70 80 90]]

Matrix 2:
 [[5 4 3]
 [2 1 0]
 [9 8 7]]

Subtraction (Matrix1 - Matrix2):
 [[ 5 16 27]
 [38 49 60]
 [61 72 83]]


In [15]:
# Create a matrix
mat3 = np.array([[1, 2, 3],
                 [4, 5, 6]])

# Compute transpose
transpose_mat3 = np.transpose(mat3)   # OR mat3.T
print("\nMatrix:\n", mat3)
print("\nTranspose:\n", transpose_mat3)


# --------------------------
# Task 14
# --------------------------
# Create a square matrix
square_matrix = np.array([[2, 3],
                          [1, 4]])

# Compute determinant
det_val = np.linalg.det(square_matrix)
print("\nSquare Matrix:\n", square_matrix)
print("\nDeterminant:", det_val)


# --------------------------
# Task 15
# --------------------------
# Create an invertible square matrix
invertible_matrix = np.array([[4, 7],
                              [2, 6]])

# Compute inverse
inverse_matrix = np.linalg.inv(invertible_matrix)
print("\nInvertible Matrix:\n", invertible_matrix)
print("\nInverse of the Matrix:\n", inverse_matrix)


Matrix:
 [[1 2 3]
 [4 5 6]]

Transpose:
 [[1 4]
 [2 5]
 [3 6]]

Square Matrix:
 [[2 3]
 [1 4]]

Determinant: 5.000000000000001

Invertible Matrix:
 [[4 7]
 [2 6]]

Inverse of the Matrix:
 [[ 0.6 -0.7]
 [-0.2  0.4]]


In [16]:
import numpy as np

# --------------------------
# Task 16 (Eigenvalues & Eigenvectors)
# --------------------------
# Create a square matrix
square_matrix = np.array([[4, 2],
                          [1, 3]])

# Calculate eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(square_matrix)
print("Square Matrix:\n", square_matrix)
print("\nEigenvalues:\n", eigenvalues)
print("\nEigenvectors:\n", eigenvectors)

Square Matrix:
 [[4 2]
 [1 3]]

Eigenvalues:
 [5. 2.]

Eigenvectors:
 [[ 0.89442719 -0.70710678]
 [ 0.4472136   0.70710678]]


In [17]:
arr1 = np.array([15, 3, 8, 23, 7, 1])

# Sort in ascending order
sorted_arr = np.sort(arr1)
print("\nOriginal Array:", arr1)
print("Sorted Array (Ascending):", sorted_arr)


# --------------------------
# Task 18 (Sorting Descending)
# --------------------------
# Create a 1D array
arr2 = np.array([42, 17, 56, 3, 29])

# Sort ascending first, then reverse for descending
sorted_desc = np.sort(arr2)[::-1]
print("\nOriginal Array:", arr2)
print("Sorted Array (Descending):", sorted_desc)


Original Array: [15  3  8 23  7  1]
Sorted Array (Ascending): [ 1  3  7  8 15 23]

Original Array: [42 17 56  3 29]
Sorted Array (Descending): [56 42 29 17  3]


In [18]:
import numpy as np

# --------------------------
# Task 17
# --------------------------
# Create a 1D array
arr1 = np.array([1, 4, 7, 10, 2, 8, 5])

# Find indices of elements greater than 5
indices = np.where(arr1 > 5)
print("1D Array:", arr1)
print("Indices of elements > 5:", indices[0])
print("Elements > 5:", arr1[indices])


# --------------------------
# Task 18
# --------------------------
# Create a 2D array
arr2 = np.array([[12, 4, 7],
                 [1, 9, 3],
                 [6, 2, 8]])

# Sort each row independently
sorted_rows = np.sort(arr2, axis=1)
print("\nOriginal 2D Array:\n", arr2)
print("Row-wise Sorted Array:\n", sorted_rows)


# --------------------------
# Task 19
# --------------------------
# Create another 2D array
arr3 = np.array([[15, 2, 9],
                 [7, 11, 3],
                 [4, 8, 6]])

# Sort each column individually
sorted_columns = np.sort(arr3, axis=0)
print("\nOriginal 2D Array:\n", arr3)
print("Column-wise Sorted Array:\n", sorted_columns)


# --------------------------
# Task 20
# --------------------------
# Create a 1D array with city names
cities = np.array(["Delhi", "Mumbai", "Chennai", "Kolkata", "Bengaluru", "Hyderabad"])

# Sort the array alphabetically
sorted_cities = np.sort(cities)
print("\nOriginal City Array:\n", cities)
print("Sorted City Array:\n", sorted_cities)

1D Array: [ 1  4  7 10  2  8  5]
Indices of elements > 5: [2 3 5]
Elements > 5: [ 7 10  8]

Original 2D Array:
 [[12  4  7]
 [ 1  9  3]
 [ 6  2  8]]
Row-wise Sorted Array:
 [[ 4  7 12]
 [ 1  3  9]
 [ 2  6  8]]

Original 2D Array:
 [[15  2  9]
 [ 7 11  3]
 [ 4  8  6]]
Column-wise Sorted Array:
 [[ 4  2  3]
 [ 7  8  6]
 [15 11  9]]

Original City Array:
 ['Delhi' 'Mumbai' 'Chennai' 'Kolkata' 'Bengaluru' 'Hyderabad']
Sorted City Array:
 ['Bengaluru' 'Chennai' 'Delhi' 'Hyderabad' 'Kolkata' 'Mumbai']


In [19]:
import numpy as np

# Create a 1D array
arr = np.array([12, 5, 8, 3, 15, 7])

# Sort in ascending order
sorted_arr = np.sort(arr)

# Print result
print("Ascending order:", sorted_arr)


Ascending order: [ 3  5  7  8 12 15]


In [20]:
import numpy as np

# Create a 1D array
arr = np.array([12, 5, 8, 3, 15, 7])

# Sort in descending order
sorted_desc = np.sort(arr)[::-1]

# Print result
print("Descending order:", sorted_desc)


Descending order: [15 12  8  7  5  3]


: 