In [10]:
import numpy as np

arr=np.arange(10)
print(arr)

zero=np.zeros(5)
print(zero)

print(np.zeros((3,3)))

print(np.eye(3))

[0 1 2 3 4 5 6 7 8 9]
[0. 0. 0. 0. 0.]
[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


In [14]:
a=np.arange(1,6)
b=np.arange(10,15)

print(a)
print(b)
print(a+b)

[1 2 3 4 5]
[10 11 12 13 14]
[11 13 15 17 19]


In [18]:
arr=np.arange(10)
slice=arr[5:16]

second=arr[::2]
print(slice)
print(second)

[5 6 7 8 9]
[0 2 4 6 8]


In [26]:
rand=np.random.uniform(0,10,(3,3))

f=rand[:2,:2]
l=rand[-1]

print(rand)
print(f)
print(l)

arr=np.arange(12)
reshaped=arr.reshape(3,4)
print(reshaped)

[[6.98308959 2.92731307 8.81996925]
 [3.65689464 0.84456246 7.45518407]
 [2.70156462 9.06186496 0.95496904]]
[[6.98308959 2.92731307]
 [3.65689464 0.84456246]]
[2.70156462 9.06186496 0.95496904]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [30]:
matrix_4x4 = np.random.randint(1, 21, (4, 4))

print("Matrix:\n", matrix_4x4)
print("Sum:", matrix_4x4.sum())
print("Mean:", matrix_4x4.mean())
print("Max:", matrix_4x4.max())
print("Min:", matrix_4x4.min())

print("Row-wise sum:", matrix_4x4.sum(axis=1))
print("Column-wise sum:", matrix_4x4.sum(axis=0))
print(matrix_4x4.sum(axis=1))


Matrix:
 [[15  2  2  1]
 [ 8 13  3 17]
 [ 1  9  9  4]
 [ 5  2  4  1]]
Sum: 96
Mean: 6.0
Max: 17
Min: 1
Row-wise sum: [20 41 23 12]
Column-wise sum: [29 26 18 23]
[20 41 23 12]


In [31]:
A = np.random.randint(1, 5, (3, 3))
B = np.random.randint(1, 5, (3, 3))

dot_product = np.dot(A, B)

matrix_2x3 = np.array([[1, 2, 3], [4, 5, 6]])
transpose_matrix = matrix_2x3.T

print(dot_product)
print(transpose_matrix)


[[15 19 19]
 [15 19 19]
 [ 8 12 14]]
[[1 4]
 [2 5]
 [3 6]]


In [33]:
rand_float = np.random.rand(3, 3)
print(rand_float)

large_array = np.random.uniform(0, 100, 1000)

print("Standard Deviation:", np.std(large_array))
print("Variance:", np.var(large_array))


[[0.70635227 0.22934113 0.15504974]
 [0.1834998  0.38629621 0.59768617]
 [0.51835526 0.1587051  0.82672273]]
Standard Deviation: 29.407560020308043
Variance: 864.80458634802


In [41]:
M1 = np.array([[1, 2], [3, 4]])
M2 = np.array([[5, 6], [7, 8]])

print(M1 + M2)
print(M1 - M2)
print(M1 * M2)

matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix.T)

square_matrix = np.array([[2, 3], [1, 4]])
determinant = np.linalg.det(square_matrix)

print("Determinant:", determinant)



invertible_matrix = np.array([[4, 7], [2, 6]])
inverse_matrix = np.linalg.inv(invertible_matrix)

print("Inverse:\n", inverse_matrix)



eig_matrix = np.array([[2, 0], [0, 3]])
eigenvalues, eigenvectors = np.linalg.eig(eig_matrix)

print("Eigenvalues:", eigenvalues)
print("Eigenvectors:\n", eigenvectors)



[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[1 4]
 [2 5]
 [3 6]]
Determinant: 5.000000000000001
Inverse:
 [[ 0.6 -0.7]
 [-0.2  0.4]]
Eigenvalues: [2. 3.]
Eigenvectors:
 [[1. 0.]
 [0. 1.]]


In [43]:
arr = np.array([5, 2, 9, 1, 7])
sorted_arr = np.sort(arr)

print(sorted_arr)

descending_arr = np.sort(arr)[::-1]
print(descending_arr)

indices = np.where(arr > 5)
print(indices)

matrix = np.array([[3, 1, 2],
                   [9, 7, 8],
                   [6, 5, 4]])

# Sort each row
row_sorted = np.sort(matrix, axis=1)

# Sort each column
column_sorted = np.sort(matrix, axis=0)

print("Row-wise sorted:\n", row_sorted)
print("Column-wise sorted:\n", column_sorted)



[1 2 5 7 9]
[9 7 5 2 1]
(array([2, 4], dtype=int64),)
Row-wise sorted:
 [[1 2 3]
 [7 8 9]
 [4 5 6]]
Column-wise sorted:
 [[3 1 2]
 [6 5 4]
 [9 7 8]]
