In [2]:
import pandas as pd
s=pd.Series([1,2,3,4,5])


In [54]:
print(s)
df=pd.DataFrame({"names":["Harry", "Sounak","Pratik","Amzeed"],"marks":[100,56,45,55]})
print(df)

0    1
1    2
2    3
3    4
4    5
dtype: int64
    names  marks
0   Harry    100
1  Sounak     56
2  Pratik     45
3  Amzeed     55


In [4]:
print(df)

    names  marks
0   Harry    100
1  Sounak     56
2  Pratik     45
3  Amzeed     55


In [5]:
df=pd.read_csv("Book2.csv")
               

In [6]:
print(df)
df.describe()
df.head()
df.tail()


    id    name
0    1  sandip
1    2   rahul
2    3     piu
3    4    ullu
4    5   rahul
5    6     hoo
6    7     joy
7    8     swe
8    9     sde
9   10      qa
10  11     wet
11  12     sda
12  13     ssd
13  14       a
14  15       d
15  16      vf
16  17      tg
17  18     vbr
18  19      rg
19  20      rb
20  21     rgt
21  22     hth
22  23      tg


id name
18  19   rg
19  20   rb
20  21  rgt
21  22  hth
22  23   tg

In [7]:
df["id"].describe()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   id      23 non-null     int64 
 1   name    23 non-null     object
dtypes: int64(1), object(1)
memory usage: 500.0+ bytes


In [8]:
df.describe()

id
count  23.00000
mean   12.00000
std     6.78233
min     1.00000
25%     6.50000
50%    12.00000
75%    17.50000
max    23.00000

In [9]:
df["id"]

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
Name: id, dtype: int64

In [10]:
type(df["id"])

pandas.core.series.Series

In [11]:
df.iloc[0]

id           1
name    sandip
Name: 0, dtype: object

In [12]:
df2=pd.read_csv("Book2.csv")

In [13]:
df2.head()

id    name
0   1  sandip
1   2   rahul
2   3     piu
3   4    ullu
4   5   rahul

In [14]:
df.dropna()

id    name
0    1  sandip
1    2   rahul
2    3     piu
3    4    ullu
4    5   rahul
5    6     hoo
6    7     joy
7    8     swe
8    9     sde
9   10      qa
10  11     wet
11  12     sda
12  13     ssd
13  14       a
14  15       d
15  16      vf
16  17      tg
17  18     vbr
18  19      rg
19  20      rb
20  21     rgt
21  22     hth
22  23      tg

In [16]:
df2.fillna(0)

id    name
0    1  sandip
1    2   rahul
2    3     piu
3    4    ullu
4    5   rahul
5    6     hoo
6    7     joy
7    8     swe
8    9     sde
9   10      qa
10  11     wet
11  12     sda
12  13     ssd
13  14       a
14  15       d
15  16      vf
16  17      tg
17  18     vbr
18  19      rg
19  20      rb
20  21     rgt
21  22     hth
22  23      tg

In [17]:
df.rename(columns={"name":"Name"})

id    Name
0    1  sandip
1    2   rahul
2    3     piu
3    4    ullu
4    5   rahul
5    6     hoo
6    7     joy
7    8     swe
8    9     sde
9   10      qa
10  11     wet
11  12     sda
12  13     ssd
13  14       a
14  15       d
15  16      vf
16  17      tg
17  18     vbr
18  19      rg
19  20      rb
20  21     rgt
21  22     hth
22  23      tg

In [18]:
df

id    name
0    1  sandip
1    2   rahul
2    3     piu
3    4    ullu
4    5   rahul
5    6     hoo
6    7     joy
7    8     swe
8    9     sde
9   10      qa
10  11     wet
11  12     sda
12  13     ssd
13  14       a
14  15       d
15  16      vf
16  17      tg
17  18     vbr
18  19      rg
19  20      rb
20  21     rgt
21  22     hth
22  23      tg

In [20]:
df['id']=df['id'].astype(str)

In [21]:
df

id    name
0    1  sandip
1    2   rahul
2    3     piu
3    4    ullu
4    5   rahul
5    6     hoo
6    7     joy
7    8     swe
8    9     sde
9   10      qa
10  11     wet
11  12     sda
12  13     ssd
13  14       a
14  15       d
15  16      vf
16  17      tg
17  18     vbr
18  19      rg
19  20      rb
20  21     rgt
21  22     hth
22  23      tg

In [24]:
df["name"]

0     sandip
1      rahul
2        piu
3       ullu
4      rahul
5        hoo
6        joy
7        swe
8        sde
9         qa
10       wet
11       sda
12       ssd
13         a
14         d
15        vf
16        tg
17       vbr
18        rg
19        rb
20       rgt
21       hth
22        tg
Name: name, dtype: object

In [25]:
df["name"][0]

'sandip'

In [26]:
len(df)

23

In [27]:
df["zeros"]=[0 for i in range(len(df))]

In [28]:
df

id    name  zeros
0    1  sandip      0
1    2   rahul      0
2    3     piu      0
3    4    ullu      0
4    5   rahul      0
5    6     hoo      0
6    7     joy      0
7    8     swe      0
8    9     sde      0
9   10      qa      0
10  11     wet      0
11  12     sda      0
12  13     ssd      0
13  14       a      0
14  15       d      0
15  16      vf      0
16  17      tg      0
17  18     vbr      0
18  19      rg      0
19  20      rb      0
20  21     rgt      0
21  22     hth      0
22  23      tg      0

In [39]:
def fx(a):
    i=1
    return i+1
df["zeros + 1"]=df["zeros"].apply(fx)

In [40]:
df

id    name  zeros  zeros + 1
0    1  sandip      0          2
1    2   rahul      0          2
2    3     piu      0          2
3    4    ullu      0          2
4    5   rahul      0          2
5    6     hoo      0          2
6    7     joy      0          2
7    8     swe      0          2
8    9     sde      0          2
9   10      qa      0          2
10  11     wet      0          2
11  12     sda      0          2
12  13     ssd      0          2
13  14       a      0          2
14  15       d      0          2
15  16      vf      0          2
16  17      tg      0          2
17  18     vbr      0          2
18  19      rg      0          2
19  20      rb      0          2
20  21     rgt      0          2
21  22     hth      0          2
22  23      tg      0          2

In [44]:
df.to_csv("Book3.csv")

In [43]:
df

id    name  zeros  zeros + 1
0    1  sandip      0          2
1    2   rahul      0          2
2    3     piu      0          2
3    4    ullu      0          2
4    5   rahul      0          2
5    6     hoo      0          2
6    7     joy      0          2
7    8     swe      0          2
8    9     sde      0          2
9   10      qa      0          2
10  11     wet      0          2
11  12     sda      0          2
12  13     ssd      0          2
13  14       a      0          2
14  15       d      0          2
15  16      vf      0          2
16  17      tg      0          2
17  18     vbr      0          2
18  19      rg      0          2
19  20      rb      0          2
20  21     rgt      0          2
21  22     hth      0          2
22  23      tg      0          2

In [45]:
df1=pd.DataFrame({"name":["Harry","Rohan","Shubham","Divya","Aparna","Samantha","Khusi"],"marks":[100,54,200,34,78,55,90]})

In [47]:
df1

name  marks
0     Harry    100
1     Rohan     54
2   Shubham    200
3     Divya     34
4    Aparna     78
5  Samantha     55
6     Khusi     90

In [48]:
pd.concat([df1,df2])

name  marks    id
0      Harry  100.0   NaN
1      Rohan   54.0   NaN
2    Shubham  200.0   NaN
3      Divya   34.0   NaN
4     Aparna   78.0   NaN
5   Samantha   55.0   NaN
6      Khusi   90.0   NaN
0     sandip    NaN   1.0
1      rahul    NaN   2.0
2        piu    NaN   3.0
3       ullu    NaN   4.0
4      rahul    NaN   5.0
5        hoo    NaN   6.0
6        joy    NaN   7.0
7        swe    NaN   8.0
8        sde    NaN   9.0
9         qa    NaN  10.0
10       wet    NaN  11.0
11       sda    NaN  12.0
12       ssd    NaN  13.0
13         a    NaN  14.0
14         d    NaN  15.0
15        vf    NaN  16.0
16        tg    NaN  17.0
17       vbr    NaN  18.0
18        rg    NaN  19.0
19        rb    NaN  20.0
20       rgt    NaN  21.0
21       hth    NaN  22.0
22        tg    NaN  23.0

In [49]:
df3=pd.DataFrame({"name":["Akashi","Priyanka"],"roll":[1244,908]})

In [50]:
df3

name  roll
0    Akashi  1244
1  Priyanka   908

In [52]:
pd.concat([df1,df3])

name  marks    roll
0     Harry  100.0     NaN
1     Rohan   54.0     NaN
2   Shubham  200.0     NaN
3     Divya   34.0     NaN
4    Aparna   78.0     NaN
5  Samantha   55.0     NaN
6     Khusi   90.0     NaN
0    Akashi    NaN  1244.0
1  Priyanka    NaN   908.0

In [53]:
pd.merge(df1,df3,on="name")

Empty DataFrame
Columns: [name, marks, roll]
Index: []

Numpy Education
NUMPY EDUCATION

Numpy Education


In [4]:
import numpy as np
print("hello world")

myarr=np.array([[2,4,5,7]],np.int64)

myarr[0,1]

hello world


4

In [5]:
myarr.shape

(1, 4)

In [6]:
myarr

array([[2, 4, 5, 7]], dtype=int64)

In [7]:
myarr[0,1]=45

In [8]:
myarr

array([[ 2, 45,  5,  7]], dtype=int64)

In [9]:
import sklearn

In [10]:
i=45

In [11]:
print(7)

7


In [12]:
i

45

In [13]:
myarr[0,1]

45

Array Creation: Conversion from other python structures

In [14]:
listarray=np.array([[4,3,9],[3,0,5],[0,2,1]])
listarray

array([[4, 3, 9],
       [3, 0, 5],
       [0, 2, 1]])

In [15]:
listarray.dtype

dtype('int32')

In [16]:
listarray.shape

(3, 3)

In [17]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [18]:
zeros=np.zeros((2,5))

In [19]:
zeros.dtype

dtype('float64')

In [20]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [21]:
rng=np.arange(15)

In [22]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [23]:
lspace=np.linspace(1,5,4)

In [24]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [25]:
emp_like=np.empty_like(lspace)

In [26]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [27]:
ide=np.identity(45)

In [28]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [29]:
ide.shape

(45, 45)

In [30]:
arr=np.arange(99)

In [31]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [32]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [33]:
arr=arr.ravel()

In [34]:
arr.shape

(99,)

In [35]:
x=[[1,2,4],[4,5,6],[6,9,0]]

In [36]:
ar=np.array(x)

In [37]:
ar

array([[1, 2, 4],
       [4, 5, 6],
       [6, 9, 0]])

In [38]:
ar.sum(axis=0)

array([11, 16, 10])

In [39]:
ar.sum(axis=1)

array([ 7, 15, 15])

In [40]:
ar.T

array([[1, 4, 6],
       [2, 5, 9],
       [4, 6, 0]])

In [41]:
for item in ar.flat:
    print(item)

1
2
4
4
5
6
6
9
0


In [42]:
ar.ndim  """two dimensional"""

SyntaxError: invalid syntax (1158809010.py, line 1)

In [43]:
ar.size

9

In [44]:
ar.nbytes

36

In [45]:
one=np.array([1,2,33,4])

In [46]:
one.argmax()

2

In [47]:
one.argmin()

0

In [48]:
one.argsort()

array([0, 1, 3, 2], dtype=int64)

In [49]:
one.argsort()

array([0, 1, 3, 2], dtype=int64)

In [51]:
"""43:22"""

ar.argmax(axis=0)
ar.argmax(axis=1)


array([2, 2, 1], dtype=int64)

In [52]:
ar.ravel()

array([1, 2, 4, 4, 5, 6, 6, 9, 0])

In [55]:
ar.reshape((9,1))

array([[1],
       [2],
       [4],
       [4],
       [5],
       [6],
       [6],
       [9],
       [0]])

In [61]:
ar.reshape((9,))

array([1, 2, 4, 4, 5, 6, 6, 9, 0])

In [62]:
ar2=np.array([[2,4,6],[4,8,0],[1,6,8]])

In [66]:
ar2

array([[2, 4, 6],
       [4, 8, 0],
       [1, 6, 8]])

In [67]:
ar

array([[1, 2, 4],
       [4, 5, 6],
       [6, 9, 0]])

In [64]:
ar+ar2

array([[ 3,  6, 10],
       [ 8, 13,  6],
       [ 7, 15,  8]])

In [68]:
[52,45]+[8,78]

[52, 45, 8, 78]

In [69]:
ar*ar2

array([[ 2,  8, 24],
       [16, 40,  0],
       [ 6, 54,  0]])

In [70]:
np.sqrt(ar)

array([[1.        , 1.41421356, 2.        ],
       [2.        , 2.23606798, 2.44948974],
       [2.44948974, 3.        , 0.        ]])

In [71]:
ar2.max()

8

In [72]:
np.where(ar>5)

(array([1, 2, 2], dtype=int64), array([2, 0, 1], dtype=int64))

In [77]:
import sys

In [78]:
py_ar=[2,45,780]
np_ar=np.array(py_ar)

In [79]:
sys.getsizeof(1)*len(py_ar)

84

In [81]:
np_ar.itemsize*np_ar.size

12

In [82]:
https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html

SyntaxError: invalid syntax (1653793619.py, line 1)

In [83]:
https://pandas.pydata.org/docs/user_guide/basics.html

SyntaxError: invalid syntax (131826960.py, line 1)