In [101]:
import pandas as pd
s=pd.Series([1,2,3,4,5])


In [3]:
print(s)
df=pd.DataFrame({"names":["Harry", "Sounak","Pratik","Amzeed"],"marks":[100,56,45,55]})
print(df)

0    1
1    2
2    3
3    4
4    5
dtype: int64
    names  marks
0   Harry    100
1  Sounak     56
2  Pratik     45
3  Amzeed     55


In [4]:
print(df)

    names  marks
0   Harry    100
1  Sounak     56
2  Pratik     45
3  Amzeed     55


In [5]:
df=pd.read_csv("Book2.csv")
               

In [6]:
print(df)
df.describe()
df.head()
df.tail()


    Unnamed: 0  id    name  zeros  zeros + 1
0            0   1  sandip      0          2
1            1   2   rahul      0          2
2            2   3     piu      0          2
3            3   4    ullu      0          2
4            4   5   rahul      0          2
5            5   6     hoo      0          2
6            6   7     joy      0          2
7            7   8     swe      0          2
8            8   9     sde      0          2
9            9  10      qa      0          2
10          10  11     wet      0          2
11          11  12     sda      0          2
12          12  13     ssd      0          2
13          13  14       a      0          2
14          14  15       d      0          2
15          15  16      vf      0          2
16          16  17      tg      0          2
17          17  18     vbr      0          2
18          18  19      rg      0          2
19          19  20      rb      0          2
20          20  21     rgt      0          2
21        

Unnamed: 0  id name  zeros  zeros + 1
18          18  19   rg      0          2
19          19  20   rb      0          2
20          20  21  rgt      0          2
21          21  22  hth      0          2
22          22  23   tg      0          2

In [7]:
df["id"].describe()
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  23 non-null     int64 
 1   id          23 non-null     int64 
 2   name        23 non-null     object
 3   zeros       23 non-null     int64 
 4   zeros + 1   23 non-null     int64 
dtypes: int64(4), object(1)
memory usage: 1.0+ KB


In [8]:
df.describe()

Unnamed: 0        id  zeros  zeros + 1
count    23.00000  23.00000   23.0       23.0
mean     11.00000  12.00000    0.0        2.0
std       6.78233   6.78233    0.0        0.0
min       0.00000   1.00000    0.0        2.0
25%       5.50000   6.50000    0.0        2.0
50%      11.00000  12.00000    0.0        2.0
75%      16.50000  17.50000    0.0        2.0
max      22.00000  23.00000    0.0        2.0

In [9]:
df["id"]

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
Name: id, dtype: int64

In [10]:
type(df["id"])

pandas.core.series.Series

In [11]:
df.iloc[0]

Unnamed: 0         0
id                 1
name          sandip
zeros              0
zeros + 1          2
Name: 0, dtype: object

In [12]:
df2=pd.read_csv("Book2.csv")

In [13]:
df2.head()

Unnamed: 0  id    name  zeros  zeros + 1
0           0   1  sandip      0          2
1           1   2   rahul      0          2
2           2   3     piu      0          2
3           3   4    ullu      0          2
4           4   5   rahul      0          2

In [14]:
df.dropna()

Unnamed: 0  id    name  zeros  zeros + 1
0            0   1  sandip      0          2
1            1   2   rahul      0          2
2            2   3     piu      0          2
3            3   4    ullu      0          2
4            4   5   rahul      0          2
5            5   6     hoo      0          2
6            6   7     joy      0          2
7            7   8     swe      0          2
8            8   9     sde      0          2
9            9  10      qa      0          2
10          10  11     wet      0          2
11          11  12     sda      0          2
12          12  13     ssd      0          2
13          13  14       a      0          2
14          14  15       d      0          2
15          15  16      vf      0          2
16          16  17      tg      0          2
17          17  18     vbr      0          2
18          18  19      rg      0          2
19          19  20      rb      0          2
20          20  21     rgt      0          2
21          21  22     hth      0          2
22          22  23      tg      0          2

In [15]:
df2.fillna(0)

Unnamed: 0  id    name  zeros  zeros + 1
0            0   1  sandip      0          2
1            1   2   rahul      0          2
2            2   3     piu      0          2
3            3   4    ullu      0          2
4            4   5   rahul      0          2
5            5   6     hoo      0          2
6            6   7     joy      0          2
7            7   8     swe      0          2
8            8   9     sde      0          2
9            9  10      qa      0          2
10          10  11     wet      0          2
11          11  12     sda      0          2
12          12  13     ssd      0          2
13          13  14       a      0          2
14          14  15       d      0          2
15          15  16      vf      0          2
16          16  17      tg      0          2
17          17  18     vbr      0          2
18          18  19      rg      0          2
19          19  20      rb      0          2
20          20  21     rgt      0          2
21          21  22     hth      0          2
22          22  23      tg      0          2

In [16]:
df.rename(columns={"name":"Name"})

Unnamed: 0  id    Name  zeros  zeros + 1
0            0   1  sandip      0          2
1            1   2   rahul      0          2
2            2   3     piu      0          2
3            3   4    ullu      0          2
4            4   5   rahul      0          2
5            5   6     hoo      0          2
6            6   7     joy      0          2
7            7   8     swe      0          2
8            8   9     sde      0          2
9            9  10      qa      0          2
10          10  11     wet      0          2
11          11  12     sda      0          2
12          12  13     ssd      0          2
13          13  14       a      0          2
14          14  15       d      0          2
15          15  16      vf      0          2
16          16  17      tg      0          2
17          17  18     vbr      0          2
18          18  19      rg      0          2
19          19  20      rb      0          2
20          20  21     rgt      0          2
21          21  22     hth      0          2
22          22  23      tg      0          2

In [17]:
df

Unnamed: 0  id    name  zeros  zeros + 1
0            0   1  sandip      0          2
1            1   2   rahul      0          2
2            2   3     piu      0          2
3            3   4    ullu      0          2
4            4   5   rahul      0          2
5            5   6     hoo      0          2
6            6   7     joy      0          2
7            7   8     swe      0          2
8            8   9     sde      0          2
9            9  10      qa      0          2
10          10  11     wet      0          2
11          11  12     sda      0          2
12          12  13     ssd      0          2
13          13  14       a      0          2
14          14  15       d      0          2
15          15  16      vf      0          2
16          16  17      tg      0          2
17          17  18     vbr      0          2
18          18  19      rg      0          2
19          19  20      rb      0          2
20          20  21     rgt      0          2
21          21  22     hth      0          2
22          22  23      tg      0          2

In [18]:
df['id']=df['id'].astype(str)

In [19]:
df

Unnamed: 0  id    name  zeros  zeros + 1
0            0   1  sandip      0          2
1            1   2   rahul      0          2
2            2   3     piu      0          2
3            3   4    ullu      0          2
4            4   5   rahul      0          2
5            5   6     hoo      0          2
6            6   7     joy      0          2
7            7   8     swe      0          2
8            8   9     sde      0          2
9            9  10      qa      0          2
10          10  11     wet      0          2
11          11  12     sda      0          2
12          12  13     ssd      0          2
13          13  14       a      0          2
14          14  15       d      0          2
15          15  16      vf      0          2
16          16  17      tg      0          2
17          17  18     vbr      0          2
18          18  19      rg      0          2
19          19  20      rb      0          2
20          20  21     rgt      0          2
21          21  22     hth      0          2
22          22  23      tg      0          2

In [20]:
df["name"]

0     sandip
1      rahul
2        piu
3       ullu
4      rahul
5        hoo
6        joy
7        swe
8        sde
9         qa
10       wet
11       sda
12       ssd
13         a
14         d
15        vf
16        tg
17       vbr
18        rg
19        rb
20       rgt
21       hth
22        tg
Name: name, dtype: object

In [21]:
df["name"][0]

'sandip'

In [22]:
len(df)

23

In [23]:
df["zeros"]=[0 for i in range(len(df))]

In [24]:
df

Unnamed: 0  id    name  zeros  zeros + 1
0            0   1  sandip      0          2
1            1   2   rahul      0          2
2            2   3     piu      0          2
3            3   4    ullu      0          2
4            4   5   rahul      0          2
5            5   6     hoo      0          2
6            6   7     joy      0          2
7            7   8     swe      0          2
8            8   9     sde      0          2
9            9  10      qa      0          2
10          10  11     wet      0          2
11          11  12     sda      0          2
12          12  13     ssd      0          2
13          13  14       a      0          2
14          14  15       d      0          2
15          15  16      vf      0          2
16          16  17      tg      0          2
17          17  18     vbr      0          2
18          18  19      rg      0          2
19          19  20      rb      0          2
20          20  21     rgt      0          2
21          21  22     hth      0          2
22          22  23      tg      0          2

In [25]:
def fx(a):
    i=1
    return i+1
df["zeros + 1"]=df["zeros"].apply(fx)

In [26]:
df

Unnamed: 0  id    name  zeros  zeros + 1
0            0   1  sandip      0          2
1            1   2   rahul      0          2
2            2   3     piu      0          2
3            3   4    ullu      0          2
4            4   5   rahul      0          2
5            5   6     hoo      0          2
6            6   7     joy      0          2
7            7   8     swe      0          2
8            8   9     sde      0          2
9            9  10      qa      0          2
10          10  11     wet      0          2
11          11  12     sda      0          2
12          12  13     ssd      0          2
13          13  14       a      0          2
14          14  15       d      0          2
15          15  16      vf      0          2
16          16  17      tg      0          2
17          17  18     vbr      0          2
18          18  19      rg      0          2
19          19  20      rb      0          2
20          20  21     rgt      0          2
21          21  22     hth      0          2
22          22  23      tg      0          2

In [27]:
df.to_csv("Book3.csv")

In [28]:
df

Unnamed: 0  id    name  zeros  zeros + 1
0            0   1  sandip      0          2
1            1   2   rahul      0          2
2            2   3     piu      0          2
3            3   4    ullu      0          2
4            4   5   rahul      0          2
5            5   6     hoo      0          2
6            6   7     joy      0          2
7            7   8     swe      0          2
8            8   9     sde      0          2
9            9  10      qa      0          2
10          10  11     wet      0          2
11          11  12     sda      0          2
12          12  13     ssd      0          2
13          13  14       a      0          2
14          14  15       d      0          2
15          15  16      vf      0          2
16          16  17      tg      0          2
17          17  18     vbr      0          2
18          18  19      rg      0          2
19          19  20      rb      0          2
20          20  21     rgt      0          2
21          21  22     hth      0          2
22          22  23      tg      0          2

In [29]:
df1=pd.DataFrame({"name":["Harry","Rohan","Shubham","Divya","Aparna","Samantha","Khusi"],"marks":[100,54,200,34,78,55,90]})

In [30]:
df1

name  marks
0     Harry    100
1     Rohan     54
2   Shubham    200
3     Divya     34
4    Aparna     78
5  Samantha     55
6     Khusi     90

In [31]:
pd.concat([df1,df2])

name  marks  Unnamed: 0    id  zeros  zeros + 1
0      Harry  100.0         NaN   NaN    NaN        NaN
1      Rohan   54.0         NaN   NaN    NaN        NaN
2    Shubham  200.0         NaN   NaN    NaN        NaN
3      Divya   34.0         NaN   NaN    NaN        NaN
4     Aparna   78.0         NaN   NaN    NaN        NaN
5   Samantha   55.0         NaN   NaN    NaN        NaN
6      Khusi   90.0         NaN   NaN    NaN        NaN
0     sandip    NaN         0.0   1.0    0.0        2.0
1      rahul    NaN         1.0   2.0    0.0        2.0
2        piu    NaN         2.0   3.0    0.0        2.0
3       ullu    NaN         3.0   4.0    0.0        2.0
4      rahul    NaN         4.0   5.0    0.0        2.0
5        hoo    NaN         5.0   6.0    0.0        2.0
6        joy    NaN         6.0   7.0    0.0        2.0
7        swe    NaN         7.0   8.0    0.0        2.0
8        sde    NaN         8.0   9.0    0.0        2.0
9         qa    NaN         9.0  10.0    0.0        2.0
10       wet    NaN        10.0  11.0    0.0        2.0
11       sda    NaN        11.0  12.0    0.0        2.0
12       ssd    NaN        12.0  13.0    0.0        2.0
13         a    NaN        13.0  14.0    0.0        2.0
14         d    NaN        14.0  15.0    0.0        2.0
15        vf    NaN        15.0  16.0    0.0        2.0
16        tg    NaN        16.0  17.0    0.0        2.0
17       vbr    NaN        17.0  18.0    0.0        2.0
18        rg    NaN        18.0  19.0    0.0        2.0
19        rb    NaN        19.0  20.0    0.0        2.0
20       rgt    NaN        20.0  21.0    0.0        2.0
21       hth    NaN        21.0  22.0    0.0        2.0
22        tg    NaN        22.0  23.0    0.0        2.0

In [32]:
df3=pd.DataFrame({"name":["Akashi","Priyanka"],"roll":[1244,908]})

In [33]:
df3

name  roll
0    Akashi  1244
1  Priyanka   908

In [34]:
pd.concat([df1,df3])

name  marks    roll
0     Harry  100.0     NaN
1     Rohan   54.0     NaN
2   Shubham  200.0     NaN
3     Divya   34.0     NaN
4    Aparna   78.0     NaN
5  Samantha   55.0     NaN
6     Khusi   90.0     NaN
0    Akashi    NaN  1244.0
1  Priyanka    NaN   908.0

In [35]:
pd.merge(df1,df3,on="name")

Empty DataFrame
Columns: [name, marks, roll]
Index: []

Numpy Education
NUMPY EDUCATION

Numpy Education


In [36]:
import numpy as np
print("hello world")

myarr=np.array([[2,4,5,7]],np.int64)

myarr[0,1]

hello world


4

In [37]:
myarr.shape

(1, 4)

In [38]:
myarr

array([[2, 4, 5, 7]], dtype=int64)

In [39]:
myarr[0,1]=45

In [40]:
myarr

array([[ 2, 45,  5,  7]], dtype=int64)

In [41]:
import sklearn

In [42]:
i=45

In [43]:
print(7)

7


In [44]:
i

45

In [45]:
myarr[0,1]

45

Array Creation: Conversion from other python structures

In [46]:
listarray=np.array([[4,3,9],[3,0,5],[0,2,1]])
listarray

array([[4, 3, 9],
       [3, 0, 5],
       [0, 2, 1]])

In [47]:
listarray.dtype

dtype('int32')

In [48]:
listarray.shape

(3, 3)

In [49]:
np.array({34,23,23})

array({34, 23}, dtype=object)

In [50]:
zeros=np.zeros((2,5))

In [51]:
zeros.dtype

dtype('float64')

In [52]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [53]:
rng=np.arange(15)

In [54]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [55]:
lspace=np.linspace(1,5,4)

In [56]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [57]:
emp_like=np.empty_like(lspace)

In [58]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [59]:
ide=np.identity(45)

In [60]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [61]:
ide.shape

(45, 45)

In [62]:
arr=np.arange(99)

In [63]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [64]:
arr.reshape(3,33)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [65]:
arr=arr.ravel()

In [66]:
arr.shape

(99,)

In [67]:
x=[[1,2,4],[4,5,6],[6,9,0]]

In [68]:
ar=np.array(x)

In [69]:
ar

array([[1, 2, 4],
       [4, 5, 6],
       [6, 9, 0]])

In [70]:
ar.sum(axis=0)

array([11, 16, 10])

In [71]:
ar.sum(axis=1)

array([ 7, 15, 15])

In [72]:
ar.T

array([[1, 4, 6],
       [2, 5, 9],
       [4, 6, 0]])

In [73]:
for item in ar.flat:
    print(item)

1
2
4
4
5
6
6
9
0


In [74]:
ar.ndim  """two dimensional"""

SyntaxError: invalid syntax (3826266783.py, line 1)

In [75]:
ar.size

9

In [76]:
ar.nbytes

36

In [77]:
one=np.array([1,2,33,4])

In [78]:
one.argmax()

2

In [79]:
one.argmin()

0

In [80]:
one.argsort()

array([0, 1, 3, 2], dtype=int64)

In [81]:
one.argsort()

array([0, 1, 3, 2], dtype=int64)

In [82]:
"""43:22"""

ar.argmax(axis=0)
ar.argmax(axis=1)


array([2, 2, 1], dtype=int64)

In [83]:
ar.ravel()

array([1, 2, 4, 4, 5, 6, 6, 9, 0])

In [84]:
ar.reshape((9,1))

array([[1],
       [2],
       [4],
       [4],
       [5],
       [6],
       [6],
       [9],
       [0]])

In [85]:
ar.reshape((9,))

array([1, 2, 4, 4, 5, 6, 6, 9, 0])

In [86]:
ar2=np.array([[2,4,6],[4,8,0],[1,6,8]])

In [87]:
ar2

array([[2, 4, 6],
       [4, 8, 0],
       [1, 6, 8]])

In [88]:
ar

array([[1, 2, 4],
       [4, 5, 6],
       [6, 9, 0]])

In [89]:
ar+ar2

array([[ 3,  6, 10],
       [ 8, 13,  6],
       [ 7, 15,  8]])

In [90]:
[52,45]+[8,78]

[52, 45, 8, 78]

In [91]:
ar*ar2

array([[ 2,  8, 24],
       [16, 40,  0],
       [ 6, 54,  0]])

In [92]:
np.sqrt(ar)

array([[1.        , 1.41421356, 2.        ],
       [2.        , 2.23606798, 2.44948974],
       [2.44948974, 3.        , 0.        ]])

In [93]:
ar2.max()

8

In [94]:
np.where(ar>5)

(array([1, 2, 2], dtype=int64), array([2, 0, 1], dtype=int64))

In [95]:
import sys

In [96]:
py_ar=[2,45,780]
np_ar=np.array(py_ar)

In [97]:
sys.getsizeof(1)*len(py_ar)

84

In [98]:
np_ar.itemsize*np_ar.size

12

In [99]:
https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html

SyntaxError: invalid syntax (886629713.py, line 1)

In [100]:
https://pandas.pydata.org/docs/user_guide/basics.html

SyntaxError: invalid syntax (1533733370.py, line 1)