In [ ]:
import pandas as pd #lib is used for data manipulation and analysis
import numpy as np #lib is used for numerical computations
s=pd.Series([1,2,3,4,5]) #array of numbers is created using pandas


In [ ]:
print(s)
df=pd.DataFrame({"names":["Harry", "Sounak","Pratik","Amzeed"],"marks":[100,56,45,55]}) #datframe means 2D data structure with labeled axes (rows and columns)
#creating a dataframe with names and marks as columns
print(df)

0    1
1    2
2    3
3    4
4    5
dtype: int64
    names  marks
0   Harry    100
1  Sounak     56
2  Pratik     45
3  Amzeed     55


In [4]:
print(df)

    names  marks
0   Harry    100
1  Sounak     56
2  Pratik     45
3  Amzeed     55


In [ ]:
df=pd.read_csv("Book2.csv") #reading a csv file and creating a dataframe from it
               

In [ ]:
print(df)
df.describe() #provides a statistical summary of the dataframe
df.info() #provides information about the dataframe such as data types and non-null values
df.head() #displays the first 5 rows of the dataframe
df.iloc[0] #displays the first row of the dataframe

df.tail() #displays the last 5 rows of the dataframe
df.iloc[0:2] #displays the first 2 rows of the dataframe


    Unnamed: 0  id    name  zeros  zeros + 1
0            0   1  sandip      0          2
1            1   2   rahul      0          2
2            2   3     piu      0          2
3            3   4    ullu      0          2
4            4   5   rahul      0          2
5            5   6     hoo      0          2
6            6   7     joy      0          2
7            7   8     swe      0          2
8            8   9     sde      0          2
9            9  10      qa      0          2
10          10  11     wet      0          2
11          11  12     sda      0          2
12          12  13     ssd      0          2
13          13  14       a      0          2
14          14  15       d      0          2
15          15  16      vf      0          2
16          16  17      tg      0          2
17          17  18     vbr      0          2
18          18  19      rg      0          2
19          19  20      rb      0          2
20          20  21     rgt      0          2
21        

Unnamed: 0  id name  zeros  zeros + 1
18          18  19   rg      0          2
19          19  20   rb      0          2
20          20  21  rgt      0          2
21          21  22  hth      0          2
22          22  23   tg      0          2

In [ ]:
df["id"].describe() #provides a statistical summary of the "id" column in the dataframe
df["id"].mean() #calculates the mean of the "id" column in the dataframe
df.info() #provides information about the dataframe such as data types and non-null values
df["id"].median() #calculates the median of the "id" column in the dataframe

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 23 entries, 0 to 22
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype 
---  ------      --------------  ----- 
 0   Unnamed: 0  23 non-null     int64 
 1   id          23 non-null     int64 
 2   name        23 non-null     object
 3   zeros       23 non-null     int64 
 4   zeros + 1   23 non-null     int64 
dtypes: int64(4), object(1)
memory usage: 1.0+ KB


In [8]:
df.describe()

Unnamed: 0        id  zeros  zeros + 1
count    23.00000  23.00000   23.0       23.0
mean     11.00000  12.00000    0.0        2.0
std       6.78233   6.78233    0.0        0.0
min       0.00000   1.00000    0.0        2.0
25%       5.50000   6.50000    0.0        2.0
50%      11.00000  12.00000    0.0        2.0
75%      16.50000  17.50000    0.0        2.0
max      22.00000  23.00000    0.0        2.0

In [9]:
df["id"]

0      1
1      2
2      3
3      4
4      5
5      6
6      7
7      8
8      9
9     10
10    11
11    12
12    13
13    14
14    15
15    16
16    17
17    18
18    19
19    20
20    21
21    22
22    23
Name: id, dtype: int64

In [ ]:
type(df["id"]) #displays the type of the "id" column in the dataframe 
df["id"].dtype #displays the data type of the "id" column in the dataframe

pandas.core.series.Series

In [11]:
df.iloc[0]

Unnamed: 0         0
id                 1
name          sandip
zeros              0
zeros + 1          2
Name: 0, dtype: object

In [ ]:
df2=pd.read_csv("Book2.csv") #reading a csv file and creating a dataframe from it
df2 #displays the dataframe created from the csv file

In [ ]:
df2.head() #displays the first 5 rows of the dataframe created from the csv file

Unnamed: 0  id    name  zeros  zeros + 1
0           0   1  sandip      0          2
1           1   2   rahul      0          2
2           2   3     piu      0          2
3           3   4    ullu      0          2
4           4   5   rahul      0          2

In [ ]:
df.dropna() #drops any rows with missing values from the dataframe
df.dropna(axis=0) #drops any rows with missing values from the dataframe along the row axis
df.dropna(axis=1) #drops any columns with missing values from the dataframe along the column axis
df.dropna(thresh=1) #drops any rows with less than 1 non-null value from the dataframe


Unnamed: 0  id    name  zeros  zeros + 1
0            0   1  sandip      0          2
1            1   2   rahul      0          2
2            2   3     piu      0          2
3            3   4    ullu      0          2
4            4   5   rahul      0          2
5            5   6     hoo      0          2
6            6   7     joy      0          2
7            7   8     swe      0          2
8            8   9     sde      0          2
9            9  10      qa      0          2
10          10  11     wet      0          2
11          11  12     sda      0          2
12          12  13     ssd      0          2
13          13  14       a      0          2
14          14  15       d      0          2
15          15  16      vf      0          2
16          16  17      tg      0          2
17          17  18     vbr      0          2
18          18  19      rg      0          2
19          19  20      rb      0          2
20          20  21     rgt      0          2
21          21  22     hth      0          2
22          22  23      tg      0          2

In [ ]:
df2.fillna(5) #fills any missing values in the dataframe with the value 5
df2.fillna(0) #fills any missing values in the dataframe with the value 0
df2.fillna(method="ffill") #fills any missing values in the dataframe using forward fill method
df2.fillna(method="bfill") #fills any missing values in the dataframe using backward fill method


Unnamed: 0  id    name  zeros  zeros + 1
0            0   1  sandip      0          2
1            1   2   rahul      0          2
2            2   3     piu      0          2
3            3   4    ullu      0          2
4            4   5   rahul      0          2
5            5   6     hoo      0          2
6            6   7     joy      0          2
7            7   8     swe      0          2
8            8   9     sde      0          2
9            9  10      qa      0          2
10          10  11     wet      0          2
11          11  12     sda      0          2
12          12  13     ssd      0          2
13          13  14       a      0          2
14          14  15       d      0          2
15          15  16      vf      0          2
16          16  17      tg      0          2
17          17  18     vbr      0          2
18          18  19      rg      0          2
19          19  20      rb      0          2
20          20  21     rgt      0          2
21          21  22     hth      0          2
22          22  23      tg      0          2

In [16]:
df.rename(columns={"name":"Name"})

Unnamed: 0  id    Name  zeros  zeros + 1
0            0   1  sandip      0          2
1            1   2   rahul      0          2
2            2   3     piu      0          2
3            3   4    ullu      0          2
4            4   5   rahul      0          2
5            5   6     hoo      0          2
6            6   7     joy      0          2
7            7   8     swe      0          2
8            8   9     sde      0          2
9            9  10      qa      0          2
10          10  11     wet      0          2
11          11  12     sda      0          2
12          12  13     ssd      0          2
13          13  14       a      0          2
14          14  15       d      0          2
15          15  16      vf      0          2
16          16  17      tg      0          2
17          17  18     vbr      0          2
18          18  19      rg      0          2
19          19  20      rb      0          2
20          20  21     rgt      0          2
21          21  22     hth      0          2
22          22  23      tg      0          2

In [17]:
df

Unnamed: 0  id    name  zeros  zeros + 1
0            0   1  sandip      0          2
1            1   2   rahul      0          2
2            2   3     piu      0          2
3            3   4    ullu      0          2
4            4   5   rahul      0          2
5            5   6     hoo      0          2
6            6   7     joy      0          2
7            7   8     swe      0          2
8            8   9     sde      0          2
9            9  10      qa      0          2
10          10  11     wet      0          2
11          11  12     sda      0          2
12          12  13     ssd      0          2
13          13  14       a      0          2
14          14  15       d      0          2
15          15  16      vf      0          2
16          16  17      tg      0          2
17          17  18     vbr      0          2
18          18  19      rg      0          2
19          19  20      rb      0          2
20          20  21     rgt      0          2
21          21  22     hth      0          2
22          22  23      tg      0          2

In [ ]:
df['id']=df['id'].astype(str) #converts the "id" column in the dataframe to string type
df['id'].dtype #displays the data type of the "id" column in the dataframe after conversion column in the dataframe to boolean type
df['id'].astype(object) #converts the "id" column in the dataframe to object type
df['id'].astype("category") #converts the "id" column in the dataframe to category type
df['id'].astype(int) #converts the "id" column in the dataframe to integer type
df['id'].astype(float) #converts the "id" column in the dataframe to float type
df['id'].astype(str) #converts the "id" column in the dataframe to string type
df['id'].astype(bool) #converts the "id" column in the dataframe to boolean type 
#dtype('O') means object type in pandas, which is used for string data

dtype('O')

In [19]:
df

Unnamed: 0  id    name  zeros  zeros + 1
0            0   1  sandip      0          2
1            1   2   rahul      0          2
2            2   3     piu      0          2
3            3   4    ullu      0          2
4            4   5   rahul      0          2
5            5   6     hoo      0          2
6            6   7     joy      0          2
7            7   8     swe      0          2
8            8   9     sde      0          2
9            9  10      qa      0          2
10          10  11     wet      0          2
11          11  12     sda      0          2
12          12  13     ssd      0          2
13          13  14       a      0          2
14          14  15       d      0          2
15          15  16      vf      0          2
16          16  17      tg      0          2
17          17  18     vbr      0          2
18          18  19      rg      0          2
19          19  20      rb      0          2
20          20  21     rgt      0          2
21          21  22     hth      0          2
22          22  23      tg      0          2

In [20]:
df["name"]

0     sandip
1      rahul
2        piu
3       ullu
4      rahul
5        hoo
6        joy
7        swe
8        sde
9         qa
10       wet
11       sda
12       ssd
13         a
14         d
15        vf
16        tg
17       vbr
18        rg
19        rb
20       rgt
21       hth
22        tg
Name: name, dtype: object

In [21]:
df["name"][0]

'sandip'

In [ ]:
len(df) #displays the number of rows in the dataframe
len(df.columns) #displays the number of columns in the dataframe

23

In [ ]:
df["zeros"]=[0 for i in range(len(df))] #creates a new column "zeros" in the dataframe with all values set to 0
df["zeros"]=[0]*len(df) #creates a new column "zeros" in the dataframe with all values set to 0

In [24]:
df

Unnamed: 0  id    name  zeros  zeros + 1
0            0   1  sandip      0          2
1            1   2   rahul      0          2
2            2   3     piu      0          2
3            3   4    ullu      0          2
4            4   5   rahul      0          2
5            5   6     hoo      0          2
6            6   7     joy      0          2
7            7   8     swe      0          2
8            8   9     sde      0          2
9            9  10      qa      0          2
10          10  11     wet      0          2
11          11  12     sda      0          2
12          12  13     ssd      0          2
13          13  14       a      0          2
14          14  15       d      0          2
15          15  16      vf      0          2
16          16  17      tg      0          2
17          17  18     vbr      0          2
18          18  19      rg      0          2
19          19  20      rb      0          2
20          20  21     rgt      0          2
21          21  22     hth      0          2
22          22  23      tg      0          2

In [ ]:
def fx(a): #function to add 1 to the value of a
    i=1
    return i+1
df["zeros + 1"]=df["zeros"].apply(fx) #creates a new column "zeros + 1" in the dataframe by applying the function fx to the "zeros" column

In [26]:
df

Unnamed: 0  id    name  zeros  zeros + 1
0            0   1  sandip      0          2
1            1   2   rahul      0          2
2            2   3     piu      0          2
3            3   4    ullu      0          2
4            4   5   rahul      0          2
5            5   6     hoo      0          2
6            6   7     joy      0          2
7            7   8     swe      0          2
8            8   9     sde      0          2
9            9  10      qa      0          2
10          10  11     wet      0          2
11          11  12     sda      0          2
12          12  13     ssd      0          2
13          13  14       a      0          2
14          14  15       d      0          2
15          15  16      vf      0          2
16          16  17      tg      0          2
17          17  18     vbr      0          2
18          18  19      rg      0          2
19          19  20      rb      0          2
20          20  21     rgt      0          2
21          21  22     hth      0          2
22          22  23      tg      0          2

In [ ]:
df.to_csv("Book3.csv") #saves the dataframe to a csv file named "Book3.csv"
df.to_csv("Book4.csv", index=False) #saves the dataframe to a csv file named "Book4.csv" without the index 

In [28]:
df

Unnamed: 0  id    name  zeros  zeros + 1
0            0   1  sandip      0          2
1            1   2   rahul      0          2
2            2   3     piu      0          2
3            3   4    ullu      0          2
4            4   5   rahul      0          2
5            5   6     hoo      0          2
6            6   7     joy      0          2
7            7   8     swe      0          2
8            8   9     sde      0          2
9            9  10      qa      0          2
10          10  11     wet      0          2
11          11  12     sda      0          2
12          12  13     ssd      0          2
13          13  14       a      0          2
14          14  15       d      0          2
15          15  16      vf      0          2
16          16  17      tg      0          2
17          17  18     vbr      0          2
18          18  19      rg      0          2
19          19  20      rb      0          2
20          20  21     rgt      0          2
21          21  22     hth      0          2
22          22  23      tg      0          2

In [ ]:
df1=pd.DataFrame({"name":["Harry","Rohan","Shubham","Divya","Aparna","Samantha","Khusi"],"marks":[100,54,200,34,78,55,90]})
#creating a dataframe with names and marks as columns
df1.to_csv("Book5.csv") #saves the dataframe to a csv file named "Book5.csv"

name  marks
0     Harry    100
1     Rohan     54
2   Shubham    200
3     Divya     34
4    Aparna     78
5  Samantha     55
6     Khusi     90

In [ ]:
pd.concat([df1,df2]) #concatenates two dataframes df1 and df2 vertically

name  marks  Unnamed: 0    id  zeros  zeros + 1
0      Harry  100.0         NaN   NaN    NaN        NaN
1      Rohan   54.0         NaN   NaN    NaN        NaN
2    Shubham  200.0         NaN   NaN    NaN        NaN
3      Divya   34.0         NaN   NaN    NaN        NaN
4     Aparna   78.0         NaN   NaN    NaN        NaN
5   Samantha   55.0         NaN   NaN    NaN        NaN
6      Khusi   90.0         NaN   NaN    NaN        NaN
0     sandip    NaN         0.0   1.0    0.0        2.0
1      rahul    NaN         1.0   2.0    0.0        2.0
2        piu    NaN         2.0   3.0    0.0        2.0
3       ullu    NaN         3.0   4.0    0.0        2.0
4      rahul    NaN         4.0   5.0    0.0        2.0
5        hoo    NaN         5.0   6.0    0.0        2.0
6        joy    NaN         6.0   7.0    0.0        2.0
7        swe    NaN         7.0   8.0    0.0        2.0
8        sde    NaN         8.0   9.0    0.0        2.0
9         qa    NaN         9.0  10.0    0.0        2.0
10       wet    NaN        10.0  11.0    0.0        2.0
11       sda    NaN        11.0  12.0    0.0        2.0
12       ssd    NaN        12.0  13.0    0.0        2.0
13         a    NaN        13.0  14.0    0.0        2.0
14         d    NaN        14.0  15.0    0.0        2.0
15        vf    NaN        15.0  16.0    0.0        2.0
16        tg    NaN        16.0  17.0    0.0        2.0
17       vbr    NaN        17.0  18.0    0.0        2.0
18        rg    NaN        18.0  19.0    0.0        2.0
19        rb    NaN        19.0  20.0    0.0        2.0
20       rgt    NaN        20.0  21.0    0.0        2.0
21       hth    NaN        21.0  22.0    0.0        2.0
22        tg    NaN        22.0  23.0    0.0        2.0

In [ ]:
df3=pd.DataFrame({"name":["Akashi","Priyanka"],"roll":[1244,908]}) #creating a dataframe with names and roll numbers as columns

In [33]:
df3

name  roll
0    Akashi  1244
1  Priyanka   908

In [ ]:
pd.concat([df1,df3]) #concatenates two dataframes df1 and df3 vertically

name  marks    roll
0     Harry  100.0     NaN
1     Rohan   54.0     NaN
2   Shubham  200.0     NaN
3     Divya   34.0     NaN
4    Aparna   78.0     NaN
5  Samantha   55.0     NaN
6     Khusi   90.0     NaN
0    Akashi    NaN  1244.0
1  Priyanka    NaN   908.0

In [ ]:
pd.merge(df1,df3,on="name") #merges two dataframes df1 and df3 on the "name" column

Empty DataFrame
Columns: [name, marks, roll]
Index: []

Numpy Education
NUMPY EDUCATION

Numpy Education


In [ ]:
import numpy as np
print("hello world")

myarr=np.array([[2,4,5,7]],np.int64)# creating a 1D array of integers
print(myarr[0]) #accessing the first element of the array

myarr[0,1] #accessing the second element of the first row of the array 00 01
myarr[0,2] #accessing the third element of the first row of the array  00 01 02
myarr[2,3] #third row and fourth column of the array 00 01 02 03
#                                                    10 11 12 13
#                                                    20 21 22 23

myarr[0,1]=5 #modifying the second element of the first row of the array

hello world


4

In [ ]:
myarr.shape #displays the shape of the array (number of rows, number of columns)

(1, 4)

In [38]:
myarr

array([[2, 4, 5, 7]], dtype=int64)

In [ ]:
myarr[0,1]=45 #modifying the second element of the first row of the array

In [40]:
myarr

array([[ 2, 45,  5,  7]], dtype=int64)

In [ ]:
import sklearn #lib is used for machine learning and data mining

In [42]:
i=45

In [43]:
print(7)

7


In [44]:
i

45

In [45]:
myarr[0,1]

45

Array Creation: Conversion from other python structures

In [ ]:
listarray=np.array([[4,3,9],[3,0,5],[0,2,1]]) #creating a 2D array of integers
listarray

array([[4, 3, 9],
       [3, 0, 5],
       [0, 2, 1]])

In [ ]:
listarray.dtype #displays the data type of the array elements

dtype('int32')

In [ ]:
listarray.shape #displays the shape of the array (number of rows, number of columns)

(3, 3)

In [ ]:
np.array({34,23,23}) #creating a set of integers

array({34, 23}, dtype=object)

In [ ]:
zeros=np.zeros((2,5)) #creating a 2D array of zeros with 2 rows and 5 columns

In [ ]:
zeros.dtype #displays the data type of the array elements

dtype('float64')

In [52]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
rng=np.arange(15) #creating a 1D array of integers from 0 to 14

In [54]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [102]:
lspace=np.linspace(1,5,4) #creating a 1D array of evenly spaced numbers between 1 and 5 with 4 elements
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [56]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [ ]:
emp_like=np.empty_like(lspace) #creating an empty array with the same shape as lspace

In [58]:
emp_like

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [ ]:
ide=np.identity(45) #creating a 2D identity matrix of size 45x45

In [60]:
ide

array([[1., 0., 0., ..., 0., 0., 0.],
       [0., 1., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 1., 0.],
       [0., 0., 0., ..., 0., 0., 1.]])

In [ ]:
ide.shape #displays the shape of the identity matrix (number of rows, number of columns)

(45, 45)

In [ ]:
arr=np.arange(99) #creating a 1D array of integers from 0 to 98

In [63]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [ ]:
arr.reshape(3,33) #reshaping the array into a 2D array with 3 rows and 33 columns

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15,
        16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31,
        32],
       [33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48,
        49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64,
        65],
       [66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81,
        82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97,
        98]])

In [103]:
arr=arr.ravel() #flattening the array into a 1D array
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98])

In [105]:
arr.shape #displays the shape of the flattened array (number of elements)

(99,)

In [ ]:
x=[[1,2,4],[4,5,6],[6,9,0]] #creating a 2D array of integers

In [ ]:
ar=np.array(x) #creating a numpy array from the 2D array x

In [69]:
ar

array([[1, 2, 4],
       [4, 5, 6],
       [6, 9, 0]])

In [ ]:
ar.sum(axis=0) #calculating the sum of the elements along the columns of the array

array([11, 16, 10])

In [ ]:
ar.sum(axis=1) #calculating the sum of the elements along the rows of the array

array([ 7, 15, 15])

In [ ]:
ar.T #transposing the array (swapping rows and columns)

array([[1, 4, 6],
       [2, 5, 9],
       [4, 6, 0]])

In [ ]:
for item in ar.flat: #iterating through the flattened array
    print(item)

1
2
4
4
5
6
6
9
0


In [106]:
ar.ndim  #displays the number of dimensions of the array

2

In [ ]:
ar.size #displays the total number of elements in the array

9

In [ ]:
ar.nbytes #displays the total number of bytes used by the array

36

In [ ]:
one=np.array([1,2,33,4]) #creating a 1D array of integers

In [ ]:
one.argmax() #returns the index of the maximum element in the array
one.argmin() #returns the index of the minimum element in the array

2

In [79]:
one.argmin()

0

In [ ]:
one.argsort() #returns the indices that would sort the array in ascending order

array([0, 1, 3, 2], dtype=int64)

In [81]:
one.argsort()

array([0, 1, 3, 2], dtype=int64)

In [ ]:
"""43:22"""

ar.argmax(axis=0) #returns the indices of the maximum elements along the columns of the array
ar.argmax(axis=1)


array([2, 2, 1], dtype=int64)

In [ ]:
ar.ravel() #flattening the array into a 1D array

array([1, 2, 4, 4, 5, 6, 6, 9, 0])

In [84]:
ar.reshape((9,1))

array([[1],
       [2],
       [4],
       [4],
       [5],
       [6],
       [6],
       [9],
       [0]])

In [ ]:
ar.reshape((9,)) #reshaping the array into a 1D array with 9 elements
ar.reshape((1,9)) #reshaping the array into a 2D array with 1 row and 9 columns

array([1, 2, 4, 4, 5, 6, 6, 9, 0])

In [86]:
ar2=np.array([[2,4,6],[4,8,0],[1,6,8]])

In [87]:
ar2

array([[2, 4, 6],
       [4, 8, 0],
       [1, 6, 8]])

In [88]:
ar

array([[1, 2, 4],
       [4, 5, 6],
       [6, 9, 0]])

In [ ]:
ar+ar2 #adding two arrays element-wise
ar-ar2 #subtracting two arrays element-wise

array([[ 3,  6, 10],
       [ 8, 13,  6],
       [ 7, 15,  8]])

In [ ]:
[52,45]+[8,78] #adding two lists element-wise
ar*ar2 #multiplying two arrays element-wise

[52, 45, 8, 78]

In [91]:
ar*ar2

array([[ 2,  8, 24],
       [16, 40,  0],
       [ 6, 54,  0]])

In [ ]:
np.sqrt(ar) #calculating the square root of each element in the array
np.std(ar) #calculating the standard deviation of the elements in the array

array([[1.        , 1.41421356, 2.        ],
       [2.        , 2.23606798, 2.44948974],
       [2.44948974, 3.        , 0.        ]])

In [ ]:
ar2.max() #calculating the maximum element in the array
ar2.min() #calculating the minimum element in the array

8

In [ ]:
np.where(ar>5) #returns the indices of the elements that are greater than 5 in the array

(array([1, 2, 2], dtype=int64), array([2, 0, 1], dtype=int64))

In [ ]:
import sys #lib is used for system-specific parameters and functions
import os #lib is used for operating system dependent functionality

In [ ]:
py_ar=[2,45,780] #creating a list of integers
np_ar=np.array(py_ar) #creating a numpy array from the list

In [ ]:
sys.getsizeof(1)*len(py_ar)     #calculating the size of the list in bytes

84

In [ ]:
np_ar.itemsize*np_ar.size #calculating the size of the numpy array in bytes

12

In [99]:
https://numpy.org/doc/stable/reference/generated/numpy.ndarray.html

SyntaxError: invalid syntax (886629713.py, line 1)

In [ ]:
"""https://pandas.pydata.org/docs/user_guide/basics.html"""

SyntaxError: invalid syntax (1533733370.py, line 1)